function [uvector,vvector,P,ABSolver] = AB3(Iter,...
                                      ABSolver,RKSolver,uvector,vvector,P, ...
                                      POperator,uOperator,vOperator, ...
                                      Mesh,Boundaries,Parameters,dt)

if( Iter < 4)
    [uvector,vvector,P,~] = SSPRK3_NoShape(...
                                      RKSolver,uvector,vvector,P, ...
                                      POperator,uOperator,vOperator, ...
                                      Mesh,Boundaries,Parameters,dt);
[ABSolver.du_n_dt(:,Iter),...
 ABSolver.dv_n_dt(:,Iter)] = NavierStokes_RK(uvector,vvector,P, ...
                                        POperator,uOperator,vOperator, ...
                                        Mesh,Boundaries,Parameters);

else
%% Predictor-Corrector Adams Bashforth 3rd Order
[uvector,vvector,P,ABSolver] = AB3_step_NoShape(...
                                      ABSolver,uvector,vvector, ...
                                      POperator,uOperator,vOperator, ...
                                      Mesh,Boundaries,Parameters,dt);
end

end