function [uvector,vvector,P,Error] = ImplicitRungeKutta_withShape(...
                                      Solver,uvector,vvector,P, ...
                                      POperator,uOperator,vOperator, ...
                                      Mesh,Shape,Boundaries,Parameters,dt)


%% Coefficients
NUMSTAGES = Solver.Stages;
alpha = Solver.a_s(2,1);

%% Jacobian
[Juv] = NavierStokes_RK_CoupledJacobian_withShape(uvector,vvector, ...
                                        uOperator,vOperator, ...
                                        Mesh,Shape,Boundaries,Parameters);

JCOLS = (Mesh.Nx+1)*Mesh.Ny + Mesh.Nx*(Mesh.Ny+1);
Juv = speye(JCOLS,JCOLS) - alpha*dt*Juv;

[L,U]=ilu(Juv);

%% Stage 1
% % Evaluate du/dt
[Solver.du_n_dt(:,1),...
 Solver.dv_n_dt(:,1)] = NavierStokes_RK_NoP_withShape(uvector,vvector, ...
                                        uOperator,vOperator, ...
                                        Mesh,Shape,Boundaries,Parameters);
[Solver.du_n_dt(:,1),...
 Solver.dv_n_dt(:,1)] = ApplyVelocityDerivativeWallBoundaries( ...
                              Solver.du_n_dt(:,1), ...
                              Solver.dv_n_dt(:,1),...
                              Boundaries, ...
                              Mesh.Nx,Mesh.Ny);
[Solver.du_n_dt(:,1),...
 Solver.dv_n_dt(:,1)] = ApplyVelocityDerivativeShapeBoundaries( ...
                              Solver.du_n_dt(:,1), ...
                              Solver.dv_n_dt(:,1),...
                              Shape, ...
                              Mesh.Nx,Mesh.Ny);

%% Stage N
for N = 2:(NUMSTAGES)

[Solver,~,~] = NewtonStageSolve_withShape(N,uvector,vvector, ...
                                            L,U,Juv,Solver, ...
                                            POperator,uOperator, ...
                                            vOperator,Mesh, ...
                                            Shape,Boundaries, ...
                                            Parameters,dt);
end

%% Solution
uvector = uvector + sum((dt * Solver.b.').* Solver.du_n_dt,2);
vvector = vvector + sum((dt * Solver.b.').* Solver.dv_n_dt,2);

[uvector,vvector,P] = CorrectorStep_RK_withShape(uvector,vvector, ...
                                        POperator,uOperator,vOperator, ...
                                        Mesh,Shape,Boundaries,Parameters,dt);

u_tilde = sum((dt * (Solver.b_tilde.'-Solver.b.')).* Solver.du_n_dt,2);
v_tilde = sum((dt * (Solver.b_tilde.'-Solver.b.')).* Solver.dv_n_dt,2);

u_tilde = max(abs(u_tilde));
v_tilde = max(abs(v_tilde));

Error = max(u_tilde,v_tilde);


end