function Boundaries = CreateBoundaries(leftwall,lu,lv,...
                                     rightwall,ru,rv,...
                                     bottomwall,bu,bv,...
                                     topwall,tu,tv)
%% Types Inlet, Wall, Free
Boundaries = struct('LeftWallType',leftwall,'Left_u',lu,'Left_v',lv,...
                  'RightWallType',rightwall,'Right_u',ru,'Right_v',rv,...
                  'BottomWallType',bottomwall,'Bottom_u',bu,'Bottom_v',bv,...
                  'TopWallType',topwall,'Top_u',tu,'Top_v',tv);

end