function PlotVectorField(xscale,yscale,u_centroid,v_centroid, ...
                         stepx,stepy,scalefactor,colour)
quiver(xscale,yscale, ...
          v_centroid(1:stepx:end,1:stepy:end), ...
          u_centroid(1:stepx:end,1:stepy:end), ...
          scalefactor,'LineWidth',0.85,'color',colour,'LineStyle','-');
end